// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package sqlcgen

import (
	"context"
	"strings"
)

const disableMissingAccounts = `-- name: DisableMissingAccounts :exec
UPDATE accounts
SET enabled = 0
WHERE handle NOT IN (/*SLICE:handles*/?)
`

func (q *Queries) DisableMissingAccounts(ctx context.Context, handles []string) error {
	query := disableMissingAccounts
	var queryParams []interface{}
	if len(handles) > 0 {
		for _, v := range handles {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:handles*/?", strings.Repeat(",?", len(handles))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:handles*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const upsertAccount = `-- name: UpsertAccount :exec
INSERT INTO accounts (handle, enabled, created_at_ms)
VALUES (?1, 1, ?2)
ON CONFLICT(handle) DO UPDATE SET enabled = 1
`

type UpsertAccountParams struct {
	Handle      string `json:"handle"`
	CreatedAtMs int64  `json:"created_at_ms"`
}

func (q *Queries) UpsertAccount(ctx context.Context, arg UpsertAccountParams) error {
	_, err := q.db.ExecContext(ctx, upsertAccount, arg.Handle, arg.CreatedAtMs)
	return err
}
