// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deliveries.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const claimNextDelivery = `-- name: ClaimNextDelivery :one
UPDATE deliveries
SET state = 'processing',
    attempts = attempts + 1,
    processing_owner = ?1,
    processing_expires_at_ms = ?2,
    updated_at_ms = ?3
WHERE deliveries.id = (
    SELECT candidate.id
    FROM deliveries AS candidate
    WHERE candidate.state = 'pending'
       OR (candidate.state = 'retry' AND (candidate.next_attempt_at_ms IS NULL OR candidate.next_attempt_at_ms <= ?4))
       OR (candidate.state = 'processing' AND candidate.processing_expires_at_ms <= ?5)
    ORDER BY candidate.created_at_ms ASC, candidate.id ASC
    LIMIT 1
)
RETURNING id, status_url, destination, state, attempts, next_attempt_at_ms, processing_owner, processing_expires_at_ms, telegram_message_id, sent_at_ms, last_error, created_at_ms, updated_at_ms
`

type ClaimNextDeliveryParams struct {
	ProcessingOwner       sql.NullString `json:"processing_owner"`
	ProcessingExpiresAtMs sql.NullInt64  `json:"processing_expires_at_ms"`
	UpdatedAtMs           int64          `json:"updated_at_ms"`
	ReadyAtMs             sql.NullInt64  `json:"ready_at_ms"`
	ExpiredAtMs           sql.NullInt64  `json:"expired_at_ms"`
}

func (q *Queries) ClaimNextDelivery(ctx context.Context, arg ClaimNextDeliveryParams) (Delivery, error) {
	row := q.db.QueryRowContext(ctx, claimNextDelivery,
		arg.ProcessingOwner,
		arg.ProcessingExpiresAtMs,
		arg.UpdatedAtMs,
		arg.ReadyAtMs,
		arg.ExpiredAtMs,
	)
	var i Delivery
	err := row.Scan(
		&i.ID,
		&i.StatusUrl,
		&i.Destination,
		&i.State,
		&i.Attempts,
		&i.NextAttemptAtMs,
		&i.ProcessingOwner,
		&i.ProcessingExpiresAtMs,
		&i.TelegramMessageID,
		&i.SentAtMs,
		&i.LastError,
		&i.CreatedAtMs,
		&i.UpdatedAtMs,
	)
	return i, err
}

const getDeliveryCounts = `-- name: GetDeliveryCounts :one
SELECT
    CAST(COALESCE(SUM(CASE WHEN state = 'pending' THEN 1 ELSE 0 END), 0) AS INTEGER) AS pending_count,
    CAST(COALESCE(SUM(CASE WHEN state = 'retry' THEN 1 ELSE 0 END), 0) AS INTEGER) AS retry_count,
    CAST(COALESCE(SUM(CASE WHEN state = 'dead' THEN 1 ELSE 0 END), 0) AS INTEGER) AS dead_count
FROM deliveries
`

type GetDeliveryCountsRow struct {
	PendingCount int64 `json:"pending_count"`
	RetryCount   int64 `json:"retry_count"`
	DeadCount    int64 `json:"dead_count"`
}

func (q *Queries) GetDeliveryCounts(ctx context.Context) (GetDeliveryCountsRow, error) {
	row := q.db.QueryRowContext(ctx, getDeliveryCounts)
	var i GetDeliveryCountsRow
	err := row.Scan(&i.PendingCount, &i.RetryCount, &i.DeadCount)
	return i, err
}

const insertDelivery = `-- name: InsertDelivery :exec
INSERT OR IGNORE INTO deliveries (
    status_url,
    destination,
    state,
    attempts,
    created_at_ms,
    updated_at_ms
) VALUES (
    ?1,
    ?2,
    'pending',
    0,
    ?3,
    ?4
)
`

type InsertDeliveryParams struct {
	StatusUrl   string `json:"status_url"`
	Destination string `json:"destination"`
	CreatedAtMs int64  `json:"created_at_ms"`
	UpdatedAtMs int64  `json:"updated_at_ms"`
}

func (q *Queries) InsertDelivery(ctx context.Context, arg InsertDeliveryParams) error {
	_, err := q.db.ExecContext(ctx, insertDelivery,
		arg.StatusUrl,
		arg.Destination,
		arg.CreatedAtMs,
		arg.UpdatedAtMs,
	)
	return err
}

const markDeliveryDead = `-- name: MarkDeliveryDead :exec
UPDATE deliveries
SET state = 'dead',
    processing_owner = NULL,
    processing_expires_at_ms = NULL,
    last_error = ?1,
    updated_at_ms = ?2
WHERE id = ?3
`

type MarkDeliveryDeadParams struct {
	LastError   sql.NullString `json:"last_error"`
	UpdatedAtMs int64          `json:"updated_at_ms"`
	ID          int64          `json:"id"`
}

func (q *Queries) MarkDeliveryDead(ctx context.Context, arg MarkDeliveryDeadParams) error {
	_, err := q.db.ExecContext(ctx, markDeliveryDead, arg.LastError, arg.UpdatedAtMs, arg.ID)
	return err
}

const markDeliveryRetry = `-- name: MarkDeliveryRetry :exec
UPDATE deliveries
SET state = 'retry',
    next_attempt_at_ms = ?1,
    processing_owner = NULL,
    processing_expires_at_ms = NULL,
    last_error = ?2,
    updated_at_ms = ?3
WHERE id = ?4
`

type MarkDeliveryRetryParams struct {
	NextAttemptAtMs sql.NullInt64  `json:"next_attempt_at_ms"`
	LastError       sql.NullString `json:"last_error"`
	UpdatedAtMs     int64          `json:"updated_at_ms"`
	ID              int64          `json:"id"`
}

func (q *Queries) MarkDeliveryRetry(ctx context.Context, arg MarkDeliveryRetryParams) error {
	_, err := q.db.ExecContext(ctx, markDeliveryRetry,
		arg.NextAttemptAtMs,
		arg.LastError,
		arg.UpdatedAtMs,
		arg.ID,
	)
	return err
}

const markDeliverySent = `-- name: MarkDeliverySent :exec
UPDATE deliveries
SET state = 'sent',
    telegram_message_id = ?1,
    sent_at_ms = ?2,
    processing_owner = NULL,
    processing_expires_at_ms = NULL,
    next_attempt_at_ms = NULL,
    last_error = NULL,
    updated_at_ms = ?3
WHERE id = ?4
`

type MarkDeliverySentParams struct {
	TelegramMessageID sql.NullInt64 `json:"telegram_message_id"`
	SentAtMs          sql.NullInt64 `json:"sent_at_ms"`
	UpdatedAtMs       int64         `json:"updated_at_ms"`
	ID                int64         `json:"id"`
}

func (q *Queries) MarkDeliverySent(ctx context.Context, arg MarkDeliverySentParams) error {
	_, err := q.db.ExecContext(ctx, markDeliverySent,
		arg.TelegramMessageID,
		arg.SentAtMs,
		arg.UpdatedAtMs,
		arg.ID,
	)
	return err
}

const recoverExpiredDeliveries = `-- name: RecoverExpiredDeliveries :exec
UPDATE deliveries
SET state = 'retry',
    next_attempt_at_ms = ?1,
    processing_owner = NULL,
    processing_expires_at_ms = NULL,
    last_error = CASE
        WHEN last_error IS NULL OR last_error = '' THEN 'processing lease expired'
        ELSE last_error
    END,
    updated_at_ms = ?1
WHERE state = 'processing'
  AND processing_expires_at_ms <= ?1
`

func (q *Queries) RecoverExpiredDeliveries(ctx context.Context, nowMs sql.NullInt64) error {
	_, err := q.db.ExecContext(ctx, recoverExpiredDeliveries, nowMs)
	return err
}
