// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql"
)

type Account struct {
	Handle      string `json:"handle"`
	Enabled     int64  `json:"enabled"`
	CreatedAtMs int64  `json:"created_at_ms"`
}

type Delivery struct {
	ID                    int64          `json:"id"`
	StatusUrl             string         `json:"status_url"`
	Destination           string         `json:"destination"`
	State                 string         `json:"state"`
	Attempts              int64          `json:"attempts"`
	NextAttemptAtMs       sql.NullInt64  `json:"next_attempt_at_ms"`
	ProcessingOwner       sql.NullString `json:"processing_owner"`
	ProcessingExpiresAtMs sql.NullInt64  `json:"processing_expires_at_ms"`
	TelegramMessageID     sql.NullInt64  `json:"telegram_message_id"`
	SentAtMs              sql.NullInt64  `json:"sent_at_ms"`
	LastError             sql.NullString `json:"last_error"`
	CreatedAtMs           int64          `json:"created_at_ms"`
	UpdatedAtMs           int64          `json:"updated_at_ms"`
}

type MonitorState struct {
	Key         string `json:"key"`
	Value       string `json:"value"`
	UpdatedAtMs int64  `json:"updated_at_ms"`
}

type Post struct {
	StatusUrl       string         `json:"status_url"`
	StatusID        string         `json:"status_id"`
	AccountHandle   string         `json:"account_handle"`
	ContentType     string         `json:"content_type"`
	PublishedAtMs   sql.NullInt64  `json:"published_at_ms"`
	OriginalText    sql.NullString `json:"original_text"`
	SummaryZh       string         `json:"summary_zh"`
	UncertaintyJson string         `json:"uncertainty_json"`
	FirstSeenRunID  string         `json:"first_seen_run_id"`
	FirstSeenAtMs   int64          `json:"first_seen_at_ms"`
	RawJson         string         `json:"raw_json"`
}

type Run struct {
	ID                string         `json:"id"`
	TriggerType       string         `json:"trigger_type"`
	ScheduledAtMs     sql.NullInt64  `json:"scheduled_at_ms"`
	StartedAtMs       int64          `json:"started_at_ms"`
	CompletedAtMs     sql.NullInt64  `json:"completed_at_ms"`
	WindowStartMs     int64          `json:"window_start_ms"`
	WindowEndMs       int64          `json:"window_end_ms"`
	Status            string         `json:"status"`
	GrokRunID         sql.NullString `json:"grok_run_id"`
	PostsFound        int64          `json:"posts_found"`
	PostsNew          int64          `json:"posts_new"`
	NotificationsSent int64          `json:"notifications_sent"`
	ErrorCode         sql.NullString `json:"error_code"`
	ErrorMessage      sql.NullString `json:"error_message"`
}
