// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: posts.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const getPostByStatusURL = `-- name: GetPostByStatusURL :one
SELECT status_url, status_id, account_handle, content_type, published_at_ms, original_text, summary_zh, uncertainty_json, first_seen_run_id, first_seen_at_ms, raw_json
FROM posts
WHERE status_url = ?1
`

func (q *Queries) GetPostByStatusURL(ctx context.Context, statusUrl string) (Post, error) {
	row := q.db.QueryRowContext(ctx, getPostByStatusURL, statusUrl)
	var i Post
	err := row.Scan(
		&i.StatusUrl,
		&i.StatusID,
		&i.AccountHandle,
		&i.ContentType,
		&i.PublishedAtMs,
		&i.OriginalText,
		&i.SummaryZh,
		&i.UncertaintyJson,
		&i.FirstSeenRunID,
		&i.FirstSeenAtMs,
		&i.RawJson,
	)
	return i, err
}

const insertPost = `-- name: InsertPost :execresult
INSERT OR IGNORE INTO posts (
    status_url,
    status_id,
    account_handle,
    content_type,
    published_at_ms,
    original_text,
    summary_zh,
    uncertainty_json,
    first_seen_run_id,
    first_seen_at_ms,
    raw_json
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7,
    ?8,
    ?9,
    ?10,
    ?11
)
`

type InsertPostParams struct {
	StatusUrl       string         `json:"status_url"`
	StatusID        string         `json:"status_id"`
	AccountHandle   string         `json:"account_handle"`
	ContentType     string         `json:"content_type"`
	PublishedAtMs   sql.NullInt64  `json:"published_at_ms"`
	OriginalText    sql.NullString `json:"original_text"`
	SummaryZh       string         `json:"summary_zh"`
	UncertaintyJson string         `json:"uncertainty_json"`
	FirstSeenRunID  string         `json:"first_seen_run_id"`
	FirstSeenAtMs   int64          `json:"first_seen_at_ms"`
	RawJson         string         `json:"raw_json"`
}

func (q *Queries) InsertPost(ctx context.Context, arg InsertPostParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertPost,
		arg.StatusUrl,
		arg.StatusID,
		arg.AccountHandle,
		arg.ContentType,
		arg.PublishedAtMs,
		arg.OriginalText,
		arg.SummaryZh,
		arg.UncertaintyJson,
		arg.FirstSeenRunID,
		arg.FirstSeenAtMs,
		arg.RawJson,
	)
}
