// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"
	"database/sql"
)

type Querier interface {
	ClaimNextDelivery(ctx context.Context, arg ClaimNextDeliveryParams) (Delivery, error)
	CompleteRun(ctx context.Context, arg CompleteRunParams) error
	DisableMissingAccounts(ctx context.Context, handles []string) error
	GetDeliveryCounts(ctx context.Context) (GetDeliveryCountsRow, error)
	GetLastRun(ctx context.Context) (Run, error)
	GetLastSuccessfulRun(ctx context.Context) (Run, error)
	GetPostByStatusURL(ctx context.Context, statusUrl string) (Post, error)
	GetState(ctx context.Context, key string) (string, error)
	InsertDelivery(ctx context.Context, arg InsertDeliveryParams) error
	InsertPost(ctx context.Context, arg InsertPostParams) (sql.Result, error)
	InsertRun(ctx context.Context, arg InsertRunParams) error
	MarkDeliveryDead(ctx context.Context, arg MarkDeliveryDeadParams) error
	MarkDeliveryRetry(ctx context.Context, arg MarkDeliveryRetryParams) error
	MarkDeliverySent(ctx context.Context, arg MarkDeliverySentParams) error
	RecoverExpiredDeliveries(ctx context.Context, nowMs sql.NullInt64) error
	UpsertAccount(ctx context.Context, arg UpsertAccountParams) error
	UpsertState(ctx context.Context, arg UpsertStateParams) error
}

var _ Querier = (*Queries)(nil)
