// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: runs.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const completeRun = `-- name: CompleteRun :exec
UPDATE runs
SET completed_at_ms = ?1,
    status = ?2,
    grok_run_id = ?3,
    posts_found = ?4,
    posts_new = ?5,
    notifications_sent = ?6,
    error_code = ?7,
    error_message = ?8
WHERE id = ?9
`

type CompleteRunParams struct {
	CompletedAtMs     sql.NullInt64  `json:"completed_at_ms"`
	Status            string         `json:"status"`
	GrokRunID         sql.NullString `json:"grok_run_id"`
	PostsFound        int64          `json:"posts_found"`
	PostsNew          int64          `json:"posts_new"`
	NotificationsSent int64          `json:"notifications_sent"`
	ErrorCode         sql.NullString `json:"error_code"`
	ErrorMessage      sql.NullString `json:"error_message"`
	ID                string         `json:"id"`
}

func (q *Queries) CompleteRun(ctx context.Context, arg CompleteRunParams) error {
	_, err := q.db.ExecContext(ctx, completeRun,
		arg.CompletedAtMs,
		arg.Status,
		arg.GrokRunID,
		arg.PostsFound,
		arg.PostsNew,
		arg.NotificationsSent,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.ID,
	)
	return err
}

const getLastRun = `-- name: GetLastRun :one
SELECT id, trigger_type, scheduled_at_ms, started_at_ms, completed_at_ms, window_start_ms, window_end_ms, status, grok_run_id, posts_found, posts_new, notifications_sent, error_code, error_message
FROM runs
ORDER BY started_at_ms DESC, rowid DESC
LIMIT 1
`

func (q *Queries) GetLastRun(ctx context.Context) (Run, error) {
	row := q.db.QueryRowContext(ctx, getLastRun)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.TriggerType,
		&i.ScheduledAtMs,
		&i.StartedAtMs,
		&i.CompletedAtMs,
		&i.WindowStartMs,
		&i.WindowEndMs,
		&i.Status,
		&i.GrokRunID,
		&i.PostsFound,
		&i.PostsNew,
		&i.NotificationsSent,
		&i.ErrorCode,
		&i.ErrorMessage,
	)
	return i, err
}

const getLastSuccessfulRun = `-- name: GetLastSuccessfulRun :one
SELECT id, trigger_type, scheduled_at_ms, started_at_ms, completed_at_ms, window_start_ms, window_end_ms, status, grok_run_id, posts_found, posts_new, notifications_sent, error_code, error_message
FROM runs
WHERE status = 'succeeded'
ORDER BY completed_at_ms DESC, rowid DESC
LIMIT 1
`

func (q *Queries) GetLastSuccessfulRun(ctx context.Context) (Run, error) {
	row := q.db.QueryRowContext(ctx, getLastSuccessfulRun)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.TriggerType,
		&i.ScheduledAtMs,
		&i.StartedAtMs,
		&i.CompletedAtMs,
		&i.WindowStartMs,
		&i.WindowEndMs,
		&i.Status,
		&i.GrokRunID,
		&i.PostsFound,
		&i.PostsNew,
		&i.NotificationsSent,
		&i.ErrorCode,
		&i.ErrorMessage,
	)
	return i, err
}

const insertRun = `-- name: InsertRun :exec
INSERT INTO runs (
    id,
    trigger_type,
    scheduled_at_ms,
    started_at_ms,
    completed_at_ms,
    window_start_ms,
    window_end_ms,
    status,
    grok_run_id,
    posts_found,
    posts_new,
    notifications_sent,
    error_code,
    error_message
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    NULL,
    ?5,
    ?6,
    ?7,
    NULL,
    0,
    0,
    0,
    NULL,
    NULL
)
`

type InsertRunParams struct {
	ID            string        `json:"id"`
	TriggerType   string        `json:"trigger_type"`
	ScheduledAtMs sql.NullInt64 `json:"scheduled_at_ms"`
	StartedAtMs   int64         `json:"started_at_ms"`
	WindowStartMs int64         `json:"window_start_ms"`
	WindowEndMs   int64         `json:"window_end_ms"`
	Status        string        `json:"status"`
}

func (q *Queries) InsertRun(ctx context.Context, arg InsertRunParams) error {
	_, err := q.db.ExecContext(ctx, insertRun,
		arg.ID,
		arg.TriggerType,
		arg.ScheduledAtMs,
		arg.StartedAtMs,
		arg.WindowStartMs,
		arg.WindowEndMs,
		arg.Status,
	)
	return err
}
