// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: state.sql

package sqlcgen

import (
	"context"
)

const getState = `-- name: GetState :one
SELECT value
FROM monitor_state
WHERE key = ?1
`

func (q *Queries) GetState(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRowContext(ctx, getState, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const upsertState = `-- name: UpsertState :exec
INSERT INTO monitor_state (key, value, updated_at_ms)
VALUES (?1, ?2, ?3)
ON CONFLICT(key) DO UPDATE SET
    value = excluded.value,
    updated_at_ms = excluded.updated_at_ms
`

type UpsertStateParams struct {
	Key         string `json:"key"`
	Value       string `json:"value"`
	UpdatedAtMs int64  `json:"updated_at_ms"`
}

func (q *Queries) UpsertState(ctx context.Context, arg UpsertStateParams) error {
	_, err := q.db.ExecContext(ctx, upsertState, arg.Key, arg.Value, arg.UpdatedAtMs)
	return err
}
